[package]
name = "dremio-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow-flight = "49.0.0"
polars = "0.36.2"
tokio = { version = "1.35.1", features = ["full"] }
tonic = "0.10.2"
